Repository RotorHazard/RotorHazard, pull requests merged in 2020-03, with the labels that each got.

#207 Added foreign keys and indexes.
  src/server/server.py
Labels: bug

#270 Fix LED custom color selector
  src/server/templates/race.html
  src/server/templates/settings.html
Labels: bug

#274 Add +W LED strip configs
  src/server/ws281x_leds.py
Labels: bug

#267 Split heats table
  src/server/server.py
  src/server/templates/database.html
  src/server/templates/race.html
Labels: enhancement

#268 Staging tone options
  src/server/server.py
  src/server/static/rotorhazard.js
  src/server/templates/race.html
  src/server/templates/settings.html
Labels: bug, enhancement

#273 Global event system
  src/server/eventmanager.py
  src/server/led_event_manager.py
  src/server/led_handler_bitmap.py
  src/server/led_handler_strip.py
  src/server/server.py
Labels: enhancement
